export function getSection8() {
  return `
---

# SECTION 8: Core Business Workflows, Algorithms & Data Flow Pipelines

This section provides an exhaustive technical specification of the seven foundational business workflows and core algorithms governing GBU-SDSM. Every workflow is detailed with end-to-end data flow diagrams, transaction boundaries, mathematical models, heuristic algorithms, edge case handling, and database operations.

---

## 8.1 Student Lifecycle & Account Provisioning Workflow

The student lifecycle governs every transition from initial onboarding and institutional account provisioning through semester progressions, placement recording, and alumni archival.

\`\`\`mermaid
sequenceDiagram
    autonumber
    actor Admin as Administrator / Coordinator
    participant Controller as StudentController
    participant Validator as StudentSchemaValidator
    participant Bcrypt as bcryptjs Engine
    participant DB as MySQL Database Engine (Sequelize)
    participant Mailer as NotificationService
    actor Student as Student User

    Admin->>Controller: POST /api/admin/students { studentData }
    Controller->>Validator: validateStudentPayload(studentData)
    
    alt Schema Validation Fails
        Validator-->>Controller: validationErrors[]
        Controller-->>Admin: 400 Bad Request { success: false, errors: validationErrors }
    else Validation Passes
        Controller->>DB: sequelize.transaction()
        Note over Controller,DB: Transaction Boundary Established
        Controller->>DB: User.findOne({ where: { [Op.or]: [{ email }, { enrollmentNo }] }, transaction })
        alt Duplicate Conflict Detected
            DB-->>Controller: existingRecord
            Controller->>DB: transaction.rollback()
            Controller-->>Admin: 409 Conflict { message: "Enrollment number or email already registered" }
        else Uniqueness Verified
            Controller->>Bcrypt: hash(defaultPassword, 10)
            Bcrypt-->>Controller: passwordHash
            Controller->>DB: User.create({ email, password: passwordHash, role: 'student', isActive: true, isApproved: true }, { transaction })
            DB-->>Controller: createdUser
            Controller->>DB: Student.create({ ...studentData, userId: createdUser.id }, { transaction })
            DB-->>Controller: createdStudent
            Controller->>DB: transaction.commit()
            Note over Controller,DB: Transaction Committed Successfully
            Controller->>Mailer: dispatchWelcomeCredentials(student.email, defaultPassword)
            Controller-->>Admin: 201 Created { success: true, student: createdStudent }
            Mailer-->>Student: Email: Account Credentials & Portal Link
        end
    end
\`\`\`

### 8.1.1 Default Credential Derivation Heuristic
When a student profile is provisioned programmatically without an explicit password, the system derives an initial temporary password following the deterministic university standard:
$$\\text{Default Password} = \\text{"GBU@"} + \\text{EnrollmentNumber}$$
*(For example: \`GBU@2500100481\`)*.
Upon first successful authentication, the frontend detects that the account is flagged with \`isFirstLogin === true\`, triggering a mandatory password change modal requiring the student to establish a cryptographically secure personal password before navigating to the dashboard.

---

## 8.2 Excel Ingestion & Heuristic Header Matching Algorithm

The automated spreadsheet ingestion pipeline allows administrators and batch coordinators to import hundreds of student records from heterogeneous spreadsheet templates without requiring manual column renaming.

\`\`\`mermaid
flowchart TD
    A[Excel Upload: .xlsx / .xls / .csv] --> B[Multer Memory Buffer]
    B --> C[xlsx.read Buffer -> Sheet to JSON]
    C --> D[Extract Raw Header Row]
    D --> E[Fuzzy Heuristic Header Normalizer]
    E --> F{Required Headers Present?}
    F -- No --> G[Reject Upload: Missing Critical Fields Error]
    F -- Yes --> H[Iterate Data Rows in Memory]
    H --> I[Row-Level Data Sanitization & Type Coercion]
    I --> J{Row Valid?}
    J -- No --> K[Append to ValidationErrors Array]
    J -- Yes --> L[Prepare User & Student Record Tuple]
    K --> M{Next Row Exists?}
    L --> M
    M -- Yes --> H
    M -- No --> N[Begin Atomic Sequelize Transaction]
    N --> O[Bulk Insert Users: User.bulkCreate]
    O --> P[Bulk Insert Students: Student.bulkCreate]
    P --> Q{Transaction Succeeded?}
    Q -- Yes --> R[Commit Transaction & Return Ingestion Summary]
    Q -- No --> S[Rollback Transaction & Return 500 Database Error]
\`\`\`

### 8.2.1 Fuzzy Header Normalization Engine
Spreadsheets generated by various university departments frequently exhibit minor header naming discrepancies (e.g., \`"Enrollment Number"\`, \`"Enrollment_No"\`, \`"Reg No"\`, \`"Registration #"\`, \`"ENROLLMENT"\`). GBU-SDSM executes a multi-stage fuzzy heuristic normalization algorithm:

1. **String Normalization Function**:
   $$\\text{clean}(s) = s.\\text{toLowerCase}().\\text{replace}(/[\\^a-z0-9]/g, '')</p>
2. **Canonical Header Alias Dictionary**:
   The ingestion engine checks cleaned header strings against an exhaustive dictionary of canonical aliases:

| Target Model Field | Canonical Name | Accepted Fuzzy Aliases & Patterns |
| :--- | :--- | :--- |
| \`enrollmentNo\` | \`enrollmentno\` | \`enrollmentno\`, \`enrollment\`, \`enrollmentnumber\`, \`regno\`, \`registrationno\`, \`admno\`, \`admissionno\`, \`rollno\`, \`rollnumber\` |
| \`name\` | \`name\` | \`name\`, \`studentname\`, \`fullname\`, \`candidatename\`, \`nameofstudent\` |
| \`email\` | \`email\` | \`email\`, \`emailid\`, \`studentemail\`, \`mail\`, \`universityemail\`, \`officialemail\` |
| \`program\` | \`program\` | \`program\`, \`programme\`, \`course\`, \`degree\` |
| \`branch\` | \`branch\` | \`branch\`, \`department\`, \`discipline\`, \`stream\`, \`specialization\` |
| \`year\` | \`year\` | \`year\`, \`academicyear\`, \`currentyear\`, \`classyear\` |
| \`semester\` | \`semester\` | \`semester\`, \`sem\`, \`currentsem\` |
| \`section\` | \`section\` | \`section\`, \`sec\`, \`batch\`, \`division\` |
| \`dob\` | \`dob\` | \`dob\`, \`dateofbirth\`, \`birthdate\`, \`bday\` |
| \`gender\` | \`gender\` | \`gender\`, \`sex\` |
| \`category\` | \`category\` | \`category\`, \`caste\`, \`socialcategory\`, \`quota\` |
| \`mobileNumber\` | \`mobilenumber\` | \`mobile\`, \`mobilenumber\`, \`phone\`, \`contact\`, \`phonenumber\`, \`studentmobile\` |
| \`cgpa\` | \`cgpa\` | \`cgpa\`, \`gpa\`, \`currentcgpa\`, \`aggregatecgpa\`, \`grade\` |
| \`placed\` | \`placed\` | \`placed\`, \`placementstatus\`, \`isplaced\`, \`placedflag\` |
| \`company\` | \`company\` | \`company\`, \`placedcompany\`, \`recruiter\`, \`employer\`, \`organization\` |
| \`package\` | \`package\` | \`package\`, \`ctc\`, \`salary\`, \`annualpackage\`, \`offeredctc\` |
| \`placementDoj\` | \`placementdoj\` | \`placementdoj\`, \`joiningdate\`, \`dojplacement\`, \`companydoj\` |
| \`placementIsPaid\`| \`placementispaid\`| \`placementispaid\`, \`paidplacement\`, \`ispaidtraining\` |
| \`hasInternship\` | \`hasinternship\` | \`hasinternship\`, \`internship\`, \`internstatus\`, \`isintern\` |
| \`internshipCompany\`| \`internshipcompany\`| \`interncompany\`, \`internshipcompany\`, \`internorganization\` |
| \`internshipDoj\` | \`internshipdoj\` | \`interndoj\`, \`internshipdoj\`, \`internshipstartdate\` |
| \`internshipDoe\` | \`internshipdoe\` | \`interndoe\`, \`internshipdoe\`, \`internshipenddate\` |
| \`internshipIsPaid\`| \`internshipispaid\`| \`internshippaid\`, \`ispaidintern\`, \`paidinternship\` |
| \`internshipStipend\`| \`internshipstipend\`| \`stipend\`, \`internstipend\`, \`monthlystipend\` |

### 8.2.2 Row-by-Row Sanitization & Type Coercion Pipeline
For every parsed row, the system runs strict type transformations:
- **Date Transformation**: Converts Excel serialized serial integers (e.g. \`45124\`) or formatted strings (\`"18/05/2004"\`, \`"2004-05-18"\`) into standardized ISO 8601 \`YYYY-MM-DD\` strings.
- **Boolean Coercion**: Values such as \`"yes"\`, \`"y"\`, \`"true"\`, \`"1"\`, \`"placed"\`, \`"paid"\` evaluate to \`true\`; all others evaluate to \`false\`.
- **Numeric Sanitization**: Strips non-numeric characters from numeric fields (e.g. \`"8.75 CGPA"\` -> \`8.75\`; \`"12 LPA"\` -> retains full string \`"12 LPA"\` for package, or coerces to float when needed).
- **Roll Number & Mobile Number Stringification**: Ensures leading zeros are preserved (preventing Excel from truncating \`01\` to \`1\`).

---

## 8.3 Multi-Tier Student Bulk Edit & Batch Migration Pipeline

The Bulk Edit system enables operators to apply synchronized modifications across cohorts of students (for instance, advancing an entire section from Semester 5 to Semester 6, or recording batch placement outcomes).

\`\`\`mermaid
flowchart TD
    A[Client Selects Students: Array of studentIds] --> B[Open BulkEditModal]
    B --> C[Operator Fills Target Fields: Semester, Section, Placement, etc.]
    C --> D[Client Dispatches: POST /api/{role}/students/bulk-edit]
    D --> E[Role Authorization & Scope Verifier]
    
    subgraph RoleSecurityCheck["Scope Enforcement Boundary"]
        E -- Admin --> F[Unrestricted Scope: WHERE id IN studentIds]
        E -- Chairperson --> G[Scope Restricted: WHERE id IN studentIds AND department IN chairDepts]
        E -- Coordinator --> H[Scope Restricted: WHERE id IN studentIds AND section = coordSection AND branch = coordBranch]
    end
    
    F --> I[Sanitize Update Object: Whitelist Modifiable Attributes]
    G --> I
    H --> I
    I --> J[Execute Atomic Query: Student.update updates, whereClause]
    J --> K[Log Batch Operation in Audit Trail]
    K --> L[Return HTTP 200: updatedCount]
    L --> M[Frontend Invalidates Query Cache & Rerenders Grid]
\`\`\`

### 8.3.1 Coordinator Data Isolation Enforcement
To guarantee that a coordinator cannot accidentally or maliciously modify students from another class section:
\`\`\`javascript
// Controller Scope Filter for Coordinator
const coordinator = await Coordinator.findOne({ where: { userId: req.user.id } });
if (!coordinator) {
  return res.status(403).json({ success: false, message: "Coordinator profile not found" });
}

const whereClause = {
  id: { [Op.in]: studentIds },
  program: coordinator.program,
  branch: coordinator.branch,
  section: coordinator.section
};

const [updatedCount] = await Student.update(sanitizedUpdates, { where: whereClause });
\`\`\`
If a compromised request injects student IDs from other sections, the \`[Op.in]\` query combined with the mandatory \`section\` constraint automatically filters them out, updating exactly zero unauthorized records.

---

## 8.4 Attendance Session Initialization, Marking & Locking Architecture

Attendance tracking represents the highest-frequency transaction system in GBU-SDSM, requiring strict transactional integrity, real-time percentage recalculation, and tamper-proof audit trails.

\`\`\`mermaid
sequenceDiagram
    autonumber
    actor Instructor as Faculty / Coordinator
    participant AttendUI as AttendanceSession Component
    participant API as AttendanceController (/api/attendance)
    participant DB as MySQL Database
    participant MetricEngine as AttendanceCalculationEngine

    Instructor->>AttendUI: Select Subject, Class, Section, Date & Session Type
    AttendUI->>API: GET /api/faculty/classes/:id/roster
    API->>DB: Student.findAll({ where: { program, branch, section } })
    DB-->>API: studentRoster[]
    API-->>AttendUI: studentRoster[] (pre-populated with status: "Present")
    
    Instructor->>AttendUI: Toggle Absentees & Add Session Remarks
    Instructor->>AttendUI: Click "Submit Attendance"
    AttendUI->>API: POST /api/attendance/sessions { sessionDetails, records[] }
    
    API->>DB: sequelize.transaction()
    Note over API,DB: Transaction Started
    API->>DB: Check for duplicate session on same date, time slot, and course
    alt Duplicate Found
        API->>DB: transaction.rollback()
        API-->>AttendUI: 409 Conflict: "Attendance session already marked for this slot"
    else No Duplicate
        API->>DB: AttendanceSession.create({ ...sessionDetails, markedBy: req.user.id })
        DB-->>API: createdSession
        API->>DB: AttendanceRecord.bulkCreate(records.map(r => ({ ...r, sessionId: createdSession.id })))
        API->>DB: transaction.commit()
        Note over API,DB: Transaction Committed
        API->>MetricEngine: triggerStudentPercentageRecalculation(studentIds)
        MetricEngine->>DB: Update cached student attendance percentages
        API-->>AttendUI: 201 Created { success: true, sessionId: createdSession.id }
    end
\`\`\`

### 8.4.1 Real-Time Attendance Percentage Calculation Formula
For any student $s$, the overall attendance percentage $P_s$ across all academic courses is computed mathematically as:

$$P_s = \\left( \\frac{\\sum_{i=1}^{M} W(\\text{status}_i)}{\\sum_{i=1}^{M} E_i} \\right) \\times 100$$

Where:
- $M$ is the total number of sessions conducted for which student $s$ was eligible.
- $W(\\text{status}_i)$ is the status weighting function:
  $$W(\\text{status}_i) = \\begin{cases} 
  1.0 & \\text{if status} = \\text{'Present'} \\\\
  0.5 & \\text{if status} = \\text{'Late'} \\\\
  1.0 & \\text{if status} = \\text{'Excused'} \\text{ (Duty / Medical Leave)} \\\\
  0.0 & \\text{if status} = \\text{'Absent'}
  \\end{cases}$$
- $E_i = 1$ represents an eligible conducted session.
- **Institutional Compliance Rules**:
  - $P_s \\ge 75.0\\%$: **Compliant** (Eligible for End-Semester Examinations).
  - $65.0\\% \\le P_s < 75.0\\%$: **Warning / Condonation Required** (Eligible only with Dean approval on medical/institutional grounds).
  - $P_s < 65.0\\%$: **Critical Defaulter** (Strictly debarred from sitting for examinations).

### 8.4.2 Attendance Session Locking & 24-Hour Edit Window
To maintain the legal and academic integrity of attendance records:
1. **Creation & Initial Edit Window**: Upon creation, the session status is \`isLocked = false\`. The original instructor who marked the session can modify individual attendance records within a strict 24-hour grace window.
2. **Automatic Session Locking**: Once 24 hours elapse from \`sessionDate\`, background cron jobs or read interceptors treat the session as locked.
3. **Manual Session Locking**: Batch Coordinators or Administrators can invoke \`PUT /api/attendance/sessions/:id/lock\` at any point to permanently finalize the records.
4. **Administrative Override**: Only users with role \`admin\` possess the authorization to edit a locked session. Any administrative override mandates an explicit audit log entry detailing the reason for the historical change.

---

## 8.5 Faculty Teaching Assignment & Roster Binding Workflow

Faculty members in GBU-SDSM do not have static access to all students; their operational visibility is dynamically computed based on active course assignments.

\`\`\`mermaid
flowchart TD
    A[Chairperson or Admin] -->|Assign Course & Section| B[FacultyAssignment Record Created]
    B --> C[(faculty_assignments Table)]
    C -->|Maps facultyId to program, branch, semester, section, subjectCode| D[Dynamic Roster Resolution]
    
    subgraph FacultyPortal["Faculty Operational Session"]
        E[Faculty Logs In] --> F[GET /api/faculty/classes]
        F --> G[Query faculty_assignments WHERE facultyId = me]
        G --> H[Render Assigned Classes Dashboard]
        H -->|Selects Class A| I[GET /api/faculty/classes/:id/roster]
        I --> J[Query students WHERE program, branch, section MATCH assignment]
        J --> K[Display Live Student Roster for Attendance & Messaging]
    end
    
    D -.-> J
\`\`\`

---

## 8.6 Scoped Cross-Role Messaging & Communication Dispatch Engine

GBU-SDSM incorporates a multi-channel communication engine that routes announcements, notifications, and direct queries while enforcing strict recipient boundaries.

\`\`\`mermaid
flowchart LR
    Sender([Sender: Faculty / Coord / Admin]) --> Router{Recipient Type?}
    Router -- Individual --> Single[Direct Message: recipientId = targetUserId]
    Router -- Class --> QueryClass[Resolve Roster: students WHERE program, branch, section]
    Router -- Universal --> CheckAdmin{Role is Admin?}
    
    CheckAdmin -- Yes --> BroadcastAll[Multi-cast: All Active Users]
    CheckAdmin -- No --> Deny[403 Forbidden: Universal Broadcast Restricted to Admin]
    
    QueryClass --> MultiInsert[Batch Insert to messages Table]
    Single --> InsertSingle[Insert to messages Table]
    BroadcastAll --> MultiInsert
    
    MultiInsert --> NotifyUsers([Recipients See Unread Counter Increment])
    InsertSingle --> NotifyUsers
\`\`\`

---

## 8.7 Data Isolation & Security Partitioning Engine

GBU-SDSM enforces multi-tenant style data isolation within a shared relational database. Security rules are compiled into a centralized query filter matrix:

\`\`\`javascript
function buildTenantScope(user) {
  switch (user.role) {
    case 'admin':
      return {}; // Universal scope: unrestricted access

    case 'chairperson':
      // Scoped to all programs/classes associated with the chairperson
      return {
        program: { [Op.in]: user.assignedPrograms }
      };

    case 'coordinator':
      // Scoped strictly to the coordinator's single assigned class batch
      return {
        program: user.assignedProgram,
        branch: user.assignedBranch,
        section: user.assignedSection
      };

    case 'faculty':
      // Scoped to classes where an active FacultyAssignment exists
      return {
        [Op.or]: user.assignedClasses.map(c => ({
          program: c.program,
          branch: c.branch,
          section: c.section
        }))
      };

    case 'student':
      // Scoped strictly to the student's individual identity
      return {
        userId: user.id
      };

    default:
      return { id: -1 }; // Deny all
  }
}
\`\`\`
This architectural pattern guarantees that data leaks between classes or departments are prevented at the SQL generation layer, irrespective of which controller invokes the query.
`;
}
